export const pagesData = [
    { name: "Контакты", link: "/contacts" },
    { name: "сведения", link: "/about_clinic" },
    { name: "о клинике", link: "/about_clinic" },
    { name: "график работы", link: "/working_hours" },
    { name: "режим работы", link: "/working_hours" },
    { name: "лицензии", link: "/licenses" },
    { name: "отзывы", link: "/reviews" },
    { name: "Терапия", link: "/therapy" },
    { name: "Терапевт", link: "/therapist" },
    { name: "Терапевты", link: "/therapist" },
    { name: "Гинекология", link: "/gynecology" },
    { name: "Гинекологи", link: "/gynecologists" },
    { name: "Гинеколог", link: "/gynecologists" },
    { name: "Хирургия", link: "/surgery" },
    { name: "Хирург", link: "/surgeon" },
    { name: "Хирурги", link: "/surgeon" },
    { name: "Урология", link: "/urology" },
    { name: "Уролог", link: "/urologist" },
    { name: "Урология", link: "/urologist" },
    { name: "Неврология", link: "/neurology" },
    { name: "неврологи", link: "/neurologist" },
    { name: "невролог", link: "/neurologist" },
    { name: "оториголарингология", link: "/otorhinolaryngology" },
    { name: "оториголаринголог", link: "/otolaryngologist" },
    { name: "оториголарингологи", link: "/otolaryngologist" },
    { name: "офтальмология", link: "/ophthalmology" },
    { name: "офтальмолог", link: "/ophthalmologist" },
    { name: "офтальмологи", link: "/ophthalmologist" },
    { name: "Стоматология", link: "/dentistry" },
    { name: "Стоматолог", link: "/dentist" },
    { name: "Стоматологи", link: "/dentist" },
    { name: "Контакты", link: "/contacts" },
    { name: "Консультация", link: "/consultations" },
    { name: "Лучевая диагностика", link: "radio_diagnosis" },
    { name: "Эндоскопическая диагностика", link: "/endoscopic_diagnostics" },
    { name: "Ультразвуковая диагностика", link: "/ultrasound_diagnostics" },
    { name: "Молекулярно-генетические исследования", link: "/molecular_genetic_study" },
]